### PR TITLE
Fetch Grocery List now  re-renders when buttons clicked

### LINKED ISSUE #4: Add callback function to buttons
**Should add to:**
- All
- Completed
- Uncompleted

### PR DESCRIPTION
**Pull request by Annie1790**
This closes #4 

**Fetch Grocery List now  re-renders when any ListButtons clicked:**

 `fetchGroceryList(e)`  is passed as prop to ListButtons.jsx, to re-render when user clicks on "All", or "Completed", or "Uncompleted".

**What it does:**
- When page is reloaded, `useEffect` is fetching "All" grocery list item,
- If user clicks on any ListButtons, takes the button's target value and fetching with this value,
- re-renders page

I also did some styling, which is fixing overflowing in mobile version

### CODE REVIEW

**Comment by Annie1790** [comment]
I was also experimenting with forceUpdate, but did not work, therefore I removed it.

**Review by igalex — CHANGES_REQUESTED** [review]
Nice but it only have some interesting behaviour here that isn't super nice.

**Comment by Annie1790** [comment]
Hi @igalex ,
Can you have a look on the latest commit please? 
Thank you!

**Review by igalex — APPROVED** [review]
lgtm

**Pull request merged**
